var weather=function(){var tmp=0;var style='qq';var SWther={w:[{}],add:{}};var SWther={};this.getWeather=function(city,type){$.getScript("http://php.weather.sina.com.cn/iframe/index/w_cl.php?code=js&day=2&city="+city+"&dfc=3",function(){if(type=='js'){echo(city);}});}
this.getStyle=function(type){style=type;}
this.help=function(type){if(type=='ver'){alert('大陆仔天气预报 \n JS版 v1.0');}
else if(type=='about'){alert('大陆仔版权所有 \n 获取最新程序 \n daluzai.net')}
else if(type=='style'){alert('目前共支持两种皮肤\n unknow 和 qq');}else{alert('错误的参数请求\n 系统帮助程序包含了 ver、about、style');}}
function dis_img(weather){if(style=='unknow'){var forder='unknow';}
else{var forder='qq';}
var style_img="uisy/skin/weather/"+forder+"/s_13.png";if(weather.indexOf("多云")!==-1||weather.indexOf("晴")!==-1){style_img="uisy/skin/weather/"+forder+"/s_1.png";}else if(weather.indexOf("多云")!==-1&&weather.indexOf("阴")!==-1){style_img="uisy/skin/weather/"+forder+"/s_2.png";}else if(weather.indexOf("阴")!==-1&&weather.indexOf("雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_3.png";}else if(weather.indexOf("晴")!==-1&&weather.indexOf("雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_12.png";}else if(weather.indexOf("晴")!==-1&&weather.indexOf("雾")!==-1){style_img="uisy/skin/weather/"+forder+"/s_12.png";}
else if(weather.indexOf("晴")!==-1){style_img="uisy/skin/weather/"+forder+"/s_13.png";}else if(weather.indexOf("多云")!==-1){style_img="uisy/skin/weather/"+forder+"/s_2.png";}else if(weather.indexOf("阵雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_3.png";}else if(weather.indexOf("小雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_3.png";}else if(weather.indexOf("中雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_4.png";}else if(weather.indexOf("大雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_5.png";}else if(weather.indexOf("暴雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_5.png";}else if(weather.indexOf("冰雹")!==-1){style_img="uisy/skin/weather/"+forder+"/s_6.png";}else if(weather.indexOf("雷阵雨")!==-1){style_img="uisy/skin/weather/"+forder+"/s_7.png";}else if(weather.indexOf("小雪")!==-1){style_img="uisy/skin/weather/"+forder+"/s_8.png";}else if(weather.indexOf("中雪")!==-1){style_img="uisy/skin/weather/"+forder+"/s_9.png";}else if(weather.indexOf("大雪")!==-1){style_img="uisy/skin/weather/"+forder+"/s_10.png";}else if(weather.indexOf("暴雪")!==-1){style_img="uisy/skin/weather/"+forder+"/s_10.png";}else if(weather.indexOf("扬沙")!==-1){style_img="uisy/skin/weather/"+forder+"/s_11.png";}else if(weather.indexOf("沙尘")!==-1){style_img="uisy/skin/weather/"+forder+"/s_11.png";}else if(weather.indexOf("雾")!==-1){style_img="uisy/skin/weather/"+forder+"/s_12.png";}else{style_img="uisy/skin/weather/"+forder+"/s_2.png";}
return style_img;}
function echo(city){if(window.SWther.w[city]===undefined){alert('请输入一个正确的城市名称');return false;}
uisy.query('return');$('#city').html(city);$('#weather').html(window.SWther.w[city][0].s1);$('#temperature').html(window.SWther.w[city][0].t1+'&deg;');$('#wind').html(window.SWther.w[city][0].p1);$('#direction').html(window.SWther.w[city][0].d1);$('#T_weather').html(window.SWther.w[city][0].s1);var T_weather_img=dis_img(window.SWther.w[city][0].s1);$('#T_weather_img').html("<img src='"+T_weather_img+"' title='"+window.SWther.w[city][0].s1+"' alt='"+window.SWther.w[city][0].s1+"' />");$('#T_temperature').html(window.SWther.w[city][0].t1+'&deg; ~ '+window.SWther.w[city][0].t2+' &deg;');$('#T_wind').html(window.SWther.w[city][0].p1);$('#T_direction').html(window.SWther.w[city][0].d1);$('#M_weather').html(window.SWther.w[city][1].s1);var M_weather_img=dis_img(window.SWther.w[city][1].s1);$('#M_weather_img').html("<img src='"+M_weather_img+"' title='"+window.SWther.w[city][1].s1+"' alt='"+window.SWther.w[city][1].s1+"' />");$('#M_temperature').html(window.SWther.w[city][1].t1+'&deg; ~ '+window.SWther.w[city][1].t2+' &deg;');$('#M_wind').html(window.SWther.w[city][1].p1);$('#M_direction').html(window.SWther.w[city][1].d1);$('#L_weather').html(window.SWther.w[city][2].s1);var L_weather_img=dis_img(window.SWther.w[city][2].s1);$('#L_weather_img').html("<img src='"+L_weather_img+"' title='"+window.SWther.w[city][2].s1+"' alt='"+window.SWther.w[city][2].s1+"' />");$('#L_temperature').html(window.SWther.w[city][2].t1+'&deg; ~ '+window.SWther.w[city][2].t2);$('#L_wind').html(window.SWther.w[city][2].p1);$('#L_direction').html(window.SWther.w[city][2].d1);}}
var uisy={query:function(ent){if(ent=='search'){$('#weather_sub >input').disabled===true;$('#weather_res_case').fadeOut(500,function(){$(this).addClass('common_hide')})}
else if(ent=='return'){$('#weather_sub >input').disabled===false;$('#weather_res_case').fadeIn(500,function(){$(this).removeClass('common_hide')})}}}
var onEvent={onEvent:function(){var has_daluzai=onEvent.daluzai();if(has_daluzai===true){$('#weather_sub >input').click(function(){onEvent.searchWeather();})
Enter_Ctrl('weather_search',13,"onEvent.searchWeather()");}},searchWeather:function(){uisy.query('search');var city=$('#weather_search >input').val();city=$.trim(city);weather_.getWeather(city,'js');},daluzai:function(){var has_author=$('#weather_author');if(has_author.length===0){return false;}else{has_author.click(function(){go_URL('blank','http://daluzai.net');})
return true;}},killError:function(){function killErrors(){return true;}
window.onerror=killErrors;}}